spring:
  application:
    name: service-registry

# Define the port where the Service Registry server would be running
server:
  port: 8761

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
      peer-node-read-timeout-ms: 60000