version: '3'
services:
  mysql-db:
    hostname: mysql-db
    environment:
      MYSQL_DATABASE: bookservice
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    image: 'mysql:latest'
    ports:
      - '3307:3306'
    restart: always
  mysql-db2:
    hostname: reviewservice-db
    environment:
      MYSQL_DATABASE: reviewservice
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    image: 'mysql:latest'
    ports:
      - '3306:3306'
  service-registry:
    hostname: service-registry
    image: ashoksuryap/service-registry
    ports:
      - '8761:8761'
    restart: always
  review-service:
    depends_on:
      - service-registry
      - mysql-db2
    environment:
      DB_HOST: mysql-db2
      DB_PORT: 3306
      EUREKA_HOST: service-registry
      EUREKA_PORT: 8761
    hostname: review-service
    image: ashoksuryap/review-service
    ports:
      - '8050:8050'
    restart: always
  inventory-service:
    depends_on:
      - service-registry
    environment:
      EUREKA_HOST: service-registry
      EUREKA_PORT: 8761
    hostname: inventory-service
    image: ashoksuryap/inventory-service
    ports:
      - '8060:8060'
    restart: always
  book-service:
    depends_on:
      - service-registry
      - mysql-db
      - review-service
      - inventory-service
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      EUREKA_HOST: service-registry
      EUREKA_PORT: 8761
    hostname: book-service
    image: ashoksuryap/book-service
    ports:
      - '8070:8070'
    restart: always