version: '3'
services:
  bookservicedb:
    hostname: bookservicedb
    environment:
      MYSQL_DATABASE: bookservice
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    image: 'mysql:latest'
    ports:
      - '3307:3306'
    restart: always
  reviewservicedb:
    hostname: reviewservicedb
    environment:
      MYSQL_DATABASE: reviewservice
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    image: 'mysql:latest'
    ports:
      - '3306:3306'
  eureka:
    hostname: eureka
    image: ashoksuryap/service-registry
    ports:
      - '8761:8761'
    restart: always
  reviewservice:
    depends_on:
      - eureka
      - reviewservicedb
    environment:
      DB_HOST: reviewservicedb
      DB_PORT: 3306
      EUREKA_HOST: eureka
      EUREKA_PORT: 8761
    hostname: reviewservice
    image: ashoksuryap/review-service
    ports:
      - '8050:8050'
    restart: always
  bookservice:
    depends_on:
      - eureka
      - bookservicedb
      - reviewservice
      - inventoryservice
    environment:
      DB_HOST: bookservicedb
      DB_PORT: 3306
      EUREKA_HOST: eureka
      EUREKA_PORT: 8761
    hostname: bookservice
    image: ashoksuryap/book-service
    ports:
      - '8070:8070'
    restart: always