mysql-db:
  image: 'mysql:latest'
  container_name: bookservice-db
  hostname: localhost
  ports:
    - '3307:3306'
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: bookservice
mysql-db2:
  image: 'mysql:latest'
  container_name: reviewservice-db
  hostname: localhost
  ports:
    - '3306:3306'
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: reviewservice
service-registry:
  image: ashoksuryap/service-registry
  hostname: service-registry
  ports:
    - '8761:8761'
book-service:
  image: ashoksuryap/book-service
  hostname: book-service
  links:
    - service-registry
    - mysql-db
    - review-service
    - inventory-service
  environment:
    EUREKA_HOST: service-registry
    EUREKA_PORT: 8761
    DB_HOST: localhost
    DB_PORT: 3306
  ports:
    - '8070:8070'
review-service:
  image: ashoksuryap/review-service
  hostname: review-service
  links:
    - service-registry
    - mysql-db2
  environment:
    EUREKA_HOST: service-registry
    EUREKA_PORT: 8761
    DB_HOST: localhost
    DB_PORT: 3306
  ports:
    - '8050:8050'
inventory-service:
  image: ashoksuryap/inventory-service
  hostname: inventory-service
  links:
    - service-registry
  environment:
    EUREKA_HOST: service-registry
    EUREKA_PORT: 8761
  ports:
    - '8060:8060'
