spring:
  application:
    name: api-gateway

# Define the port where the API gateway server would be running
server:
  port: 8080

# Define the Eureka server that handles service registration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
