spring:
  aop:
    proxyTargetClass: true
  application:
    name: api-gateway

# Define the port where the API gateway server would be running
server:
  port: 8080

# Define the Eureka server that handles service registration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    instance:
      prefer-ip-address: true
      leaseRenewalIntervalInSeconds: 5

zuul:
  routes:
    book-service: /books/**
    inventory-service: /inventory/**
    review-service: /reviews/**
    uaa-service:
      sensitiveHeaders:
      stripPrefix: false
  add-proxy-headers: true

logging:
  level.org.springframework.security: DEBUG
