server:
  port: 8070

feign:
  hystrix:
    enabled: "true"

spring:
  datasource:
    url:  jdbc:mysql://${db.host:localhost}:${db.port:3307}/bookservice
    username: ${db.username:root}
    password: ${db.password:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect