spring:
  application:
    name: inventory-service

# Define the port where the Widget Foundry server would be running
server:
  port: 8060

# Define the Eureka server that handles service registration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
    instance:
      prefer-ip-address: true
      leaseRenewalIntervalInSeconds: 5

